# Generated by Django 3.2.4 on 2021-07-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_rename_user_message_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
