# Generated by Django 3.2.4 on 2021-07-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0004_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
